name: CI

on: [push]

jobs:
  test:
    name: Test dotfiles on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Install dotfiles
      run: bash init.sh && fish -c "fishtape tests/*.fish"
